version: '3.5'

networks:
  prisma-network:
    name: prisma

volumes:
  mysql:

services:
  prisma:
    image: prismagraphql/prisma:1.12
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: mysql
            host: mysql
            port: 3306
            user: root
            password: prisma
            migrations: true
    networks:
      - prisma-network

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: prisma
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - prisma-network

  prisma-todo-graphql:
    image: prisma-todo-graphql
    restart: always
    build:
      context: .
      network: prisma
      args:
        prisma_server: prisma
    networks:
      - prisma-network
    ports:
      - "4000:4000"
    depends_on:
      - prisma
      - mysql
